# Generated by Django 3.0.5 on 2022-04-20 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_profile_id', models.CharField(max_length=1000)),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('full_name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=1000)),
                ('activity_type', models.CharField(max_length=1000)),
                ('event_description', models.TextField()),
                ('timestamp_created', models.DateField(auto_now_add=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('user_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_api.UserProfile')),
            ],
        ),
    ]
