# Generated by Django 3.0.5 on 2022-04-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetail',
            old_name='activity_type',
            new_name='park_name',
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='park_address',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
