# Generated by Django 3.0.5 on 2022-04-21 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0002_auto_20220421_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateField(auto_now_add=True)),
                ('event_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_api.EventDetail')),
                ('user_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_api.UserProfile')),
            ],
        ),
    ]
