# Generated by Django 3.0.5 on 2022-04-22 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0003_usergoingevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateField(auto_now_add=True)),
                ('comment_text', models.TextField()),
                ('event_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_api.EventDetail')),
                ('user_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_api.UserProfile')),
            ],
        ),
    ]
