# Generated by Django 3.0.5 on 2022-04-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0004_eventcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_device_token',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
